name: Action Sample

on:
  push:
    branches: 
      - work
      - main
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -l
      - name: execute echo command
        run: echo "Hello World!"
      - name: docker build
        run: docker build -t test .
